# s3配置
s3:
  endpoint: http://192.168.0.122:9000
  accessKey: pKZzDFNoJ4rwRKOsDgCQ
  secretKey: iRyB20GkRrUk65Ymr0qbpN2jbHck7eYMcQULTrAy
  bucketName: database
  region: us-east-1


#server:
#  port: 8070