spring:
  datasource:
    url: jdbc:mysql://localhost:3306/im
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


# s3配置
s3:
  endpoint: http://192.168.0.122:9000
  accessKey: pKZzDFNoJ4rwRKOsDgCQ
  secretKey: iRyB20GkRrUk65Ymr0qbpN2jbHck7eYMcQULTrAy
  bucketName: database
  region: us-east-1

socket:
  port: 9090