spring:
  profiles:
    active: dev

mybatis-plus:
  mapperScanPath: pers.kinson.im.chat.data.dao
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: false

# s3配置
s3:
  type: minio
